// Code generated by controller-gen. DO NOT EDIT.
package v1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubSecretSync) DeepCopyInto(out *GitHubSecretSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubSecretSync.
func (in *GitHubSecretSync) DeepCopy() *GitHubSecretSync {
	if in == nil {
		return nil
	}
	out := new(GitHubSecretSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubSecretSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubSecretSyncList) DeepCopyInto(out *GitHubSecretSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubSecretSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubSecretSyncList.
func (in *GitHubSecretSyncList) DeepCopy() *GitHubSecretSyncList {
	if in == nil {
		return nil
	}
	out := new(GitHubSecretSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubSecretSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubSecretSyncSpec) DeepCopyInto(out *GitHubSecretSyncSpec) {
	*out = *in
	in.GitHub.DeepCopyInto(&out.GitHub)
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubSecretSyncSpec.
func (in *GitHubSecretSyncSpec) DeepCopy() *GitHubSecretSyncSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubSecretSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubSecretSyncStatus) DeepCopyInto(out *GitHubSecretSyncStatus) {
	*out = *in
	if in.LastSyncedFields != nil {
		in, out := &in.LastSyncedFields, &out.LastSyncedFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubSecretSyncStatus.
func (in *GitHubSecretSyncStatus) DeepCopy() *GitHubSecretSyncStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubSecretSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubTarget) DeepCopyInto(out *GitHubTarget) {
	*out = *in
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeRepositories != nil {
		in, out := &in.ExcludeRepositories, &out.ExcludeRepositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubTarget.
func (in *GitHubTarget) DeepCopy() *GitHubTarget {
	if in == nil {
		return nil
	}
	out := new(GitHubTarget)
	in.DeepCopyInto(out)
	return out
}
