{{- range .Values.syncs }}
---
apiVersion: ghsecop.io/v1
kind: GitHubSecretSync
metadata:
  name: {{ required "syncs[].name is required" .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ghsecop.labels" $ | nindent 4 }}
spec:
  itemPath: {{ required "syncs[].itemPath is required" .itemPath | quote }}
  github:
    organization: {{ required "syncs[].github.organization is required" .github.organization | quote }}
    {{- with .github.repositories }}
    repositories:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .github.excludeRepositories }}
    excludeRepositories:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .github.includeArchived }}
    includeArchived: {{ .github.includeArchived }}
    {{- end }}
    {{- if .github.includeForks }}
    includeForks: {{ .github.includeForks }}
    {{- end }}
  {{- with .fields }}
  fields:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .secretNamePrefix }}
  secretNamePrefix: {{ . | quote }}
  {{- end }}
  {{- with .syncIntervalSeconds }}
  syncIntervalSeconds: {{ . }}
  {{- end }}
{{- end }}
